### ISSUE TITLE
Documentation build issues for crates that depend on Rustsat

### ISSUE THREAD

**Issue by Coloquinte** [chrjabs/rustsat#55]
After updating to rustsat 0.4.2, I still have issues when building a crate that depends on it on docs.rs ([log here](https://docs.rs/crate/volute/1.1.4/builds/1087800)). It seems related to cbindgen, which attempts to make network accesses.

There is a similar issue [on cbindgen](https://github.com/mozilla/cbindgen/issues/666). I'm a bit confused here, since parse_deps is already set to false in `rustsat/cbindgen.toml`.

I think exiting rustsat/build.rs early when executing on docs.rs would work, as is already done for the solvers.

**Comment by chrjabs** [comment]
Do you need a release quickly or is it okay if I wait a bit longer to have some more things to go into the next release?

**Comment by Coloquinte** [comment]
I'm fine with disabling this part of the documentation for now
