### ISSUE TITLE
Clarify relationship between Dimacs and Lit

### ISSUE THREAD

**Issue by ChrisJefferson** [chrjabs/rustsat#63]
Hi, I am currently rewriting some Python code to Rust, which uses a SAT solver, and your library seemed like a good fit.

I had one issue which I just wanted to check (and, if I'm right, it might be worth clarifying the documentation?)

I have some dimacs instances, and I know that certain variables in that dimacs are 'special' (I'm going to use them when solving, as part of my assumptions). I read in these 'special variables' from another file.

I currently read in a file as:

```
    let satinstance = instances::SatInstance::<BasicVarManager>::from_dimacs_path(&in_dimacs_path)?;
```

Then, I can get to the clauses by doing something like (yes, this is horrible, it's just for printing!)
```
    for clause in    eprimeparse.satinstance.as_cnf().0.iter() {
        print!("clause: {}", clause);
        for c in clause {
            print!("lit: {}", c);
        }
    }
```

My only issue is that when I print out, or construct lits, using (for example) `rustsat::types::Lit::new(5, true)`, then `rustsat::types::Lit::new(5, true)` seems to line up with `-6` from my input file. So there are two things I want to check:

1) Can I assume that, if I can always just subtract one to map between a number in my dimacs, and a Lit (obviously doing an absolute value first!)

2) Is `rustsat::types::Lit::new(5, true)` the negative version of a literal, and `rustsat::types::Lit::new(5, false)` the positive version?

Thank you very much for any clarification.

EDIT: Just after posting this, I've read the source, and noticed that `new`'s second argument is called `negated`, so it is supposed to be `true` if the variable is negated. I think this could be a little clearer in the documentation (I'll be honest, it's the opposite to the way I expect), I can see this isn't a simple error in `new`, or something like that.

Also, `from_ipasir` seems to guarantee the mapping I expect between dimacs and Lit objects, so then I suppose my question is are you happy to say the implementation of `from_ipasir` is fixed, and won't be optimised later, say by trying to skip unused variable IDs (which I wouldn't personally want to happen, but I wanted to check there aren't any suprises I haven't seen!)

**Comment by chrjabs** [comment]
Hey, thanks for your interest in RustSAT. In short, if you want to create variables/literals with DIMACS naming (i.e., index starting from 1 and positive/negative integers representing positive/negative literals), create them with `from_ipasir` indeed. IPASIR is a SAT solver API using the same variable naming convention as the DIMACS file format. The DIMACS file parser uses the `from_ipasir` method internally as well, so this way you are always guaranteed to get matching literals.

For a little more background, I opted to represent literals slightly differently in RustSAT. Variable indexes there start from 0 and for literals, the index is shifted by one bit to the left and the lowest bit is used to represent negation. This is mainly to make indexing vectors by literals easier.

I agree that this could be clearer in the documentation, so I'll keep this issue open until I fix that.

**Comment by chrjabs** [comment]
Forgot to mention, even though I'm not planning to change the internal literal representation, I won't say that it never will. Therefore, definitely use `from_ipasir` when reading in your additional file rather than manually subtracting one from the variable index.
