### ISSUE TITLE
simp::Glucose bug with solve_assumps

### ISSUE THREAD

**Issue by ChrisJefferson** [chrjabs/rustsat#64]
I think the solve simp::Glucose has a bug, where if you keep calling `solve_assumps`, after a few calls it starts producing rubbish.

Unfortunately this doesn't seem to show up with very tiny instances (I guess it needs to be big enough that Glucose does some "interesting simplifications"?)

I attach a little rust project which shows the problem. Basically I load a dimacs file, and try solving with two lists of assumptions -- the first gives a solution, the second fails.

Then I do a bunch of other assumption searches.

Finally, I redo the first 2 tests I did. Now, they both pass, giving the same answer. That second answer is definately wrong, as it doesn't assign variable 3=false (which is part of the assumption).

The code is fixed if I switch simp::Glucose to core::Glucose.

**Comment by ChrisJefferson** [comment]
[example-rustsat.tar.gz](https://github.com/chrjabs/rustsat/files/14753611/example-rustsat.tar.gz)

**Comment by chrjabs** [comment]
I am just looking into this a bit more. Indeed what seems to happen is that your variable 3 gets eliminated by a simplification step and Glucose simply ignores the assumption after that. So my guess of having to freeze the variables used in assumptions first is true. There is actually an assertion in Glucose that catches this case, you'll see your example code fail earlier if you turn on the debug feature for glucose.
In a future version I'll make Glucose/Minisat return an error when an assumption over an eleminated variable is given. For now, I'd recommend you to either use the non-simp version of glucose or simply cadical. While looking into this I found a bug in the `freeze_lit` function, so freezing the variables will only work once I've fixed this.

**Comment by ChrisJefferson** [comment]
Thanks. I didn't use simp::Glucose for a deep reason -- I used Glucose as I have experience of it and find for my problems it's often the best solver, then I chose simp just because simplifying seemed like a nice thing if I'm solving the same problem many times :) (except it seems not!)

**Comment by chrjabs** [comment]
When building against the `develop` branch, your example now returns the error `Error: assumption variable x0 has been eliminated by glucose simplification`. I hope this explains the underlying issue well enough. Again, the workaround for this error is either freezing all variables you might want to use as assumptions in the future or using another solver.
