### ISSUE TITLE
print statements from glucose internals

### ISSUE THREAD

**Issue by ChrisJefferson** [chrjabs/rustsat#65]
I see messages like the following coming from glucose

`c last restart ## conflicts  :  0 5`

It looks like there are `printf`s scattered throughout glucose (and possibly other solvers?) I could make a PR just to comment out this one, but I didn't know if you'd prefer to do something more consistent, and also if you wanted to just edit the solver sources or maintain patches or something?

**Comment by chrjabs** [comment]
Good point, those haven't annoyed me so far, but I can see how for some applications you would not want them. Of the top of my head I'm leaning towards a compile time option in cmake and cargo feature to turn them off. I'll give that a shot.

**Comment by ChrisJefferson** [comment]
Thanks for the quick work! These were mainly annoying while I was outputting debugging output (while investigating #64 ), but they also get outputted by my tests as well.
