### ISSUE TITLE
rustsat-cadical compilation fails on macOS + workaround

### ISSUE THREAD

**Issue by suomela** [chrjabs/rustsat#73]
FYI, I noticed that `rustsat-cadical` fails to compile on macOS.

It turned out to be caused by this issue in `cc`:
- https://github.com/rust-lang/cc-rs/issues/963
- https://github.com/rust-lang/cc-rs/issues/1001

It works fine after doing `cargo add cc@=1.0.83`.

So most likely `rustsat-cadical` will work fine once the bug in `cc` gets fixed, but I'm posting this here so that others who are struggling to get `rustsat-cadical` work will find a workaround somewhere…

**Comment by chrjabs** [comment]
Thanks for pointing this out and providing a workaround :+1:
Interesting that the macos github CI seems to not have problems. I guess this is exclusive to macos 14.

**Comment by suomela** [comment]
It fails also on my Intel iMac with macOS 12.7.4, so it doesn't seem to be exclusive to macOS 14.

**Comment by suomela** [comment]
(But my guess is that GitHub CI has got also Homebrew-Clang, while I've got just Apple-Clang and Homebrew-GCC, and this is enough to make a difference.)

**Comment by suomela** [comment]
Seems to work now, thanks to this: https://github.com/rust-lang/cc-rs/pull/1007
