### ISSUE TITLE
rustsat_minisat::simp segmentation fault

### ISSUE THREAD

**Issue by suomela** [chrjabs/rustsat#74]
Sample code:

```
use rustsat::instances::SatInstance;
use rustsat::solvers::Solve;
use std::error::Error;
use std::result::Result;

fn main() -> Result<(), Box<dyn Error>> {
    let instance: SatInstance = SatInstance::from_dimacs_path("example.txt")?;
    let mut solver = rustsat_minisat::simp::Minisat::default();
    solver.add_cnf(instance.as_cnf().0)?;
    println!("solving...");
    let res = solver.solve()?;
    println!("{res}");
    Ok(())
}
```

Input file: [example.txt](https://github.com/chrjabs/rustsat/files/14796073/example.txt)

This seems to crash every time with a "Segmentation fault" right after it prints "solving...". Tried these systems, with the same result:
- Intel iMac with macOS 12.7.4
- Apple M3 MacBook Pro with macOS 14.4
- some random Intel x86 Linux 

It works fine if I change `rustsat_minisat::simp` to e.g. `rustsat_minisat::core` (or any other solver).

Versions:
- Rust 1.77.0
- rustsat 0.4.3
- rustsat-minisat 0.2.4

**Comment by chrjabs** [comment]
Thanks for reporting. Due to a missing `virtual` specifier in minisat itself, the wrong method to add new variables was called.
This will be fixed in the next release.
