### ISSUE TITLE
"fatal runtime error: Rust cannot catch foreign exceptions"

### ISSUE THREAD

**Issue by suomela** [chrjabs/rustsat#79]
Hi, in some experiments with CaDiCaL and Minisat I managed to get this error message (on Intel-Linux):

> fatal runtime error: Rust cannot catch foreign exceptions

Some of these errors came after ≈ 40 hours of computation, so it won't be quick to reproduce, but I'm wondering if it is possible that memory allocation errors in the solver library might be reported like this? Or is it known that the solver running out of memory will be reported in a different way and this has to be something else?

**Comment by chrjabs** [comment]
Yes, this is most likely a memory allocation error in one of the C++ libraries. At least in this case I have seen the same error message before.

Longer term one could put some work into catching the C++ memory exceptions in the C-wrappers and then passing some error message to Rust, so that a nicer error can be returned. This would enable doing some cleanup tasks in Rust when this happens.

**Comment by ChrisJefferson** [comment]
One suggestion if this is fixed, based on my past experience interfacing with minisat (and many solvers are inspired by, or derived from, minisat).

It's not that hard to catch this, minisat-derived solvers throw an 'OutOfMemoryException' (which isn't a C++ standard thing).

If that happens however, from my past experience there isn't much more you can do than just `panic!` (I abort()ed in C++) with a more helpful error message, as the solver can be left in a weird state where it won't clean itself up properly if you destroy it (I don't remember all the details, but I did hit this, and obviously it's a hard thing to write proper tests for.).

When minisat catches an OutOfMemoryException minisat doesn't try to do any cleanup, it just prints "INDETERMINATE" and exits.

One thing I will mention (again, from past experience), quite a few solvers use 32-bit counts for sizes, so you might find they "run out of memory" while you still have lots of memory. I don't know if some of the more modern solvers like kissat remove this limitation (it's in minisat and glucose)

**Comment by suomela** [comment]
I'd be very happy with a panic, as long as the error message gives some hint that it is related to memory allocation.

**Comment by chrjabs** [comment]
Alright, that is a pretty solid idea now. I'll see whether I can give this a go in the near future.
