### ISSUE TITLE
Unify variable numbering with IPASIR / cnf?

### ISSUE THREAD

**Issue by ChrisJefferson** [chrjabs/rustsat#93]
I'm going to suggest something here which is probably unreasonable, but I want to suggest it anyway, to see how much support there is.

I often load dimacs fiels, and also look at cores the SAT solvers produce. I find it annoying that the default 'display' for Lit prints numbers 1 lower than the variable name in the dimacs (because in dimacs, variables are 1-indexed, but in rustsat they are 0-indexed).

I am currently workign around trhis by locally hacking the 'Display' function of 'Lit' to increment by 1. I'm not suggesting this as a global change!

I understand being '1-indexed' is weird, but also I feel that is the way the rest of the 'SAT' world behaves.

However, I'm not sure if there is any reasonable way to fix this (even if people wanted to fix it) now, but thought I would raise it.

**Comment by ChrisJefferson** [comment]
I've just thought of, for me, another to fix it -- once I've loaded my cnf from dimacs, I could just increment every variable by 1, and add a clause that says that the zero variable must be true (just to get rid of it). That also seems like a weird hack, but would line up the printing.

**Comment by chrjabs** [comment]
If we're just talking about how `Display` behaves, one could introduce a `display-ipasir` or similarly named feature that changes the behaviour of `Display` for `Lit` and `Var`. Would that be enough for what you are trying to do?

**Comment by ChrisJefferson** [comment]
That would work -- it would certainly help me. I've not actually tried doing 'features' in Rust yet, so I'm not sure how easy this is to add.

**Comment by ChrisJefferson** [comment]
I wondered if we could use a modifier, but it turns out the list of modifiers in Rust is fairly short, and none of them would be sensible to use for this (we could abuse something, but probably should do that!). I could also write `to_ipasir` a lot more, but don't really want to do that :)

**Comment by chrjabs** [comment]
Implementing this as a feature shouldn't be much work at all. If you have some time you could give that a shot, otherwise I could do it later on this week, when I am planning to finalize the 0.5.0 release.

**Comment by ChrisJefferson** [comment]
Unfortunately I'm deep in getting exams written and a paper finished (hence why I just hacked the code for now), so if you have time, great, else I can pick it up in future for a future release).
